const technologiesNameSets = [
  [
    "Angular",
    "HTML",
    "Angular Material",
    "React (TypeScript)",
    "Webpack",
    "CSS",
    "Node.js",
    "Vue.js",
    "TypeScript",
    "RxJS",
    "SASS",
    "Karma",
    "Jasmine",
  ],
  [
    "Java / Java EE",
    "C#",
    "Spring Boot",
    ".NET 8",
    "Spring",
    "ASP.NET MVC",
    "Quarkus",
    "ASP.NET Web API",
    "Hibernate (для ORM)",
    "Camunda",
    "Maven",
    "Android Studio",
    "Vault",
  ],
  ["Blitz", "Keycloak"],
  ["RabbitMQ", "Kafka", "REST API", "SOAP (WebServices)", "Gravitee"],
  [
    "Docker",
    "Kubernetes",
    "OpenShift",
    "GitLab CI/CD",
    "Jenkins",
    "SonarQube",
    "Zabbix",
    "Prometheus + Grafana",
    "bitbucket",
  ],
  [
    "Postman",
    "Swagger",
    "Insomnia",
    "kibana",
    "Java",
    "TestNG",
    "selenium",
    "Selenide",
    "Playwright",
    "Rest-assured",
  ],
  ["draw.io"],
  ["Microsoft SQLServer", "Oracle", "PostgreSQL", "MySQL"],
];

export default {
  "/index.html": {
    title: "Главная страница",
    leaders: [
      "/images/leaders/1.svg",
      "/images/leaders/2.svg",
      "/images/leaders/3.svg",
      "/images/leaders/4.svg",
      "/images/leaders/5.svg",
      "/images/leaders/6.svg",
      "/images/leaders/7.svg",
      "/images/leaders/8.svg",
      "/images/leaders/9.svg",
      "/images/leaders/10.svg",
      "/images/leaders/11.png",
      "/images/leaders/12.svg",
      "/images/leaders/13.png",
      "/images/leaders/14.svg",
      "/images/leaders/15.svg",
      "/images/leaders/16.webp",
    ],
    services: [
      {
        title: "Заказная разработка ПО",
        image: "/images/services/1.webp",
        items: [
          "Рефакторинг и реструктуризация кода",
          "Декомпозиции монолитных архитектур (Software Re-architecturing)",
          "Модернизация технологического стека и перенос приложений в современные среды",
        ],
      },
      {
        title: "Мобильная разработка",
        image: "/images/services/5.webp",
        imageOffset: "35%",
        items: [
          "Рефакторинг и реструктуризация кода",
          "Декомпозиции монолитных архитектур (Software Re-architecturing)",
          "Модернизация технологического стека и перенос приложений в современные среды",
        ],
      },
      {
        title: "Модернизация ИТ-систем",
        image: "/images/services/3.webp",
        items: [
          "Рефакторинг и реструктуризация кода",
          "Декомпозиции монолитных архитектур (Software Re-architecturing)",
          "Модернизация технологического стека и перенос приложений в современные среды",
        ],
      },
      {
        title: "Управление качеством ПО",
        image: "/images/services/4.webp",
        imageOffset: "35%",
        items: [
          "Рефакторинг и реструктуризация кода",
          "Декомпозиции монолитных архитектур (Software Re-architecturing)",
          "Модернизация технологического стека и перенос приложений в современные среды",
        ],
      },
      {
        title: "Заказная разработка ПО",
        image: "/images/services/1.webp",
        items: [
          "Рефакторинг и реструктуризация кода",
          "Декомпозиции монолитных архитектур (Software Re-architecturing)",
          "Модернизация технологического стека и перенос приложений в современные среды",
        ],
      },
      {
        title: "Мобильная разработка",
        image: "/images/services/5.webp",
        imageOffset: "35%",
        items: [
          "Рефакторинг и реструктуризация кода",
          "Декомпозиции монолитных архитектур (Software Re-architecturing)",
          "Модернизация технологического стека и перенос приложений в современные среды",
        ],
      },
    ],
    solutions: [
      {
        title: "Автоматизация страховых продуктов",
        image: "/images/services/1.webp",
        isReversed: true,
        items: [
          "Клиентские порталы",
          "Экстранет-порталы и партнёрские кабинеты (B2B)",
          "Интранет-порталы",
          "Системы управления доступом (IAM)",
        ],
      },
      {
        title: "Импортозамещение",
        image: "/images/services/2.webp",
        imageOffset: "35%",
        isReversed: true,
        items: [
          "Клиентские порталы",
          "Экстранет-порталы и партнёрские кабинеты (B2B)",
          "Интранет-порталы",
          "Системы управления доступом (IAM)",
        ],
      },
      {
        title: "Разработка личных кабинетов",
        image: "/images/services/3.webp",
        isReversed: true,
        items: [
          "Клиентские порталы",
          "Экстранет-порталы и партнёрские кабинеты (B2B)",
          "Интранет-порталы",
          "Системы управления доступом (IAM)",
        ],
      },
      {
        title: "Разработка HR-порталов",
        image: "/images/services/4.webp",
        imageOffset: "35%",
        isReversed: true,
        items: [
          "Клиентские порталы",
          "Экстранет-порталы и партнёрские кабинеты (B2B)",
          "Интранет-порталы",
          "Системы управления доступом (IAM)",
        ],
      },
      {
        title: "Автоматизация страховых продуктов",
        image: "/images/services/1.webp",
        isReversed: true,
        items: [
          "Клиентские порталы",
          "Экстранет-порталы и партнёрские кабинеты (B2B)",
          "Интранет-порталы",
          "Системы управления доступом (IAM)",
        ],
      },
      {
        title: "Импортозамещение",
        image: "/images/services/2.webp",
        imageOffset: "35%",
        isReversed: true,
        items: [
          "Клиентские порталы",
          "Экстранет-порталы и партнёрские кабинеты (B2B)",
          "Интранет-порталы",
          "Системы управления доступом (IAM)",
        ],
      },
    ],
    platformCards: [
      {
        image: "/images/platform/1.png",
        title: "Low code + Pro Code",
        text: "Относится к классу low code-платформа с расширенными PRO Code возможностями",
      },
      {
        image: "/images/platform/2.png",
        title: "Технологический суверенитет",
        text: "Включен в реестр российского ПО: 19858",
      },
      {
        image: "/images/platform/3.png",
        title: "Свобода от vendor lock-in",
        text: "Передаём исходный код, вы сохраняете полный контроль над проектом",
      },
      {
        image: "/images/platform/4.png",
        title: "Single-stack подход",
        text: "Ускорение работы команды разработки: один разработчик = один микросервис от логики до интерфейса",
      },
      {
        image: "/images/platform/5.png",
        title: "Гибкость на фронтенде",
        text: "Часть интерфейса формируется посредством SDUI, часть — классическим способом на Angular",
      },
    ],
    portfolio: [
      {
        href: "#",
        title: "Оптимизация маршрутов транспортной компании",
        image: "/images/portfolio-card/1.webp",
        hoveredImage: "/images/portfolio-card/1-hovered.webp",
      },
      {
        href: "#",
        title: "Автоматизация ОСАГО",
        image: "/images/portfolio-card/2.webp",
      },
      {
        href: "#",
        title: "Разработка личного кабинета для страховой компании",
        image: "/images/portfolio-card/3.webp",
      },
    ],
    newsCards: [
      {
        href: "#",
        image: "/images/news/news-1.webp",
        alt: "Турнир по футболу",
        title: "Турнир по футболу",
        date: "13.01.2026",
      },
      {
        href: "#",
        image: "/images/news/news-2.webp",
        alt: "Конференция 2025",
        title: "Конференция 2025",
        date: "10.01.2026",
      },
      {
        href: "#",
        image: "/images/news/news-3.webp",
        alt: "Разработчики взяли награду",
        title: "Разработчики взяли награду",
        date: "20.11.2025",
      },
    ],
  },
};
